# Generated by Django 3.1.4 on 2021-01-08 17:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('E_mail', models.EmailField(default='abc@gmail.com', max_length=254)),
                ('Password', models.CharField(default='none', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Manufacturer', models.CharField(max_length=30)),
                ('Price', models.BigIntegerField(default=0)),
                ('Image', models.ImageField(upload_to='store/uploads/products')),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Quantity', models.BigIntegerField(default=1)),
                ('Price', models.BigIntegerField(null=True)),
                ('Phone', models.BigIntegerField(default=0)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Date', models.DateField(default=datetime.datetime.today)),
                ('Status', models.BooleanField(default=False)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
