# Generated by Django 3.1.4 on 2021-01-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shipper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=15)),
                ('To', models.CharField(max_length=15)),
                ('Days', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Shipper',
        ),
    ]
