# Generated by Django 3.1.4 on 2021-01-10 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210110_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Date',
            new_name='Arrival_Date',
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
