# Generated by Django 3.1.4 on 2021-01-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210110_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Arrival_Date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_Date',
        ),
    ]
