# Generated by Django 3.1.4 on 2021-01-10 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210110_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Arrival_Date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
