# Generated by Django 3.1.4 on 2021-01-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210110_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Arrival_Date',
            field=models.DateField(default='10-01-21'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Date',
            field=models.DateField(default='10-01-21'),
        ),
    ]
